service: cs-quiz-app-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - !GetAtt UsersTable.Arn
        - !GetAtt QuestionsTable.Arn
        - !GetAtt ResultsTable.Arn

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: cs-quiz-api.secretjuju.kr
    basePath: 'api'
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
    certificateName: 'cs-quiz-api.secretjuju.kr'

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-users-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: nickname
            AttributeType: S
        KeySchema:
          - AttributeName: nickname
            KeyType: HASH

    QuestionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-questions-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    ResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-results-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: nickname
            AttributeType: S
          - AttributeName: score
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ScoreIndex
            KeySchema:
              - AttributeName: score
                KeyType: HASH
              - AttributeName: nickname
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
